name: On Pull Request

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: self-hosted

    # The cimg-mvn-cache is an image containing a .m2 folder warmed-up
    # with common Jahia dependencies. Using this prevents maven from
    # downloading the entire world when building.
    # More on https://github.com/Jahia/cimg-mvn-cache
    container:
      image: jahia/cimg-mvn-cache:ga_cimg_openjdk_11.0.20-node
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '11.0.19'

      - name: Build with Gradle
        run: ./gradlew shadowJar
